export const LOCALIZED_DICTIONARIES: { [lang: string]: { [key: string]: string } } = {
  en: {
    dashboard_title: "Montery System Platform",
    section_ops_header: "Ops Command Center",
    section_fan_header: "Fan Wayfinder Companion",
    section_volunteer_header: "Volunteer Field Reporting",
    label_queue_volume: "Perimeter Turnstile Queues",
    label_wait_time: "Predicted Wait Time",
    label_gate_throughput: "Throughput Flow Rate",
    label_handover_summary: "Supervisor Handover Summary",
    label_restricted_warning: "Restricted: Administrative Clearance Required",
    btn_select_role: "Select Your Persona Access Role",
    btn_step_free: "Step-Free ADA Route Option",
    spectator_deck_login: "Spectator Deck Login (FAN)",
    secure_portal_entry: "SECURE PORTAL ENTRY",
    back_to_identities: "BACK TO IDENTITIES",
    full_name: "Full Name",
    phone_number: "Phone Number",
    volunteer_name: "Volunteer Name",
    assigned_stadium: "Assigned Match Stadium",
    volunteer_number_3_digits: "Volunteer Number (3 Digits)",
    test_account_details: "TEST ACCOUNT DETAILS:",
    sync_companion_deck: "REGISTER & SYNC COMPANION DECK",
    digital_twin_workspace: "3D Digital Twin Simulation Workspace",
    home_view: "Home View",
    expand_view: "Expand View",
    shrink_view: "Shrink View",
    interactive_scanner_active: "INTERACTIVE SCANNER ACTIVE",
    incident_registry: "INCIDENT REGISTRY",
    mux_control_panel: "MUX CONTROL PANEL",
    fifa_tactical_deck: "FIFA WC 2026 TACTICAL DECK",
    step_free_routing: "Step-Free Routing",
    ada_assisted_navigation: "ADA ASSISTED NAVIGATION",
    welcome_desc: "Welcome to the Montery Smart Stadium Suite, an advanced digital twin and telemetry audit platform. Your terminal is currently unassigned. Please select your authorized operational profile below to sync sensors, initialize camera streams, and enable situational analysis matrices.",
    fan_desc: "Register your spectator identity. This data will be securely synchronized and persisted in our cloud database.",
    volunteer_desc: "Please enter your volunteer identity. Only authorized volunteers registered with official matches are permitted.",
    staff_desc: "Authenticate with your designated operations staff credentials.",
    organizer_desc: "Authenticate with high-level regional coordinator parameters.",
    role_fan_title: "Spectator Deck (FAN)",
    role_fan_desc: "General spectators. Access to layout wayfinding, concessions, transport directions, and basic arena policies.",
    role_volunteer_title: "Field Support (VOLUNTEER)",
    role_volunteer_desc: "On-the-ground volunteer stream. Help manage queues, handle visitor issues, and view real-time gate congestion reports.",
    role_staff_title: "Operations Terminal (VENUE STAFF)",
    role_staff_desc: "Control room terminals. Monitor CCTV imagery, audit ticketing anomalies, and run diagnostics on gates and facilities.",
    role_organizer_title: "Regional Coordinator (ORGANIZER)",
    role_organizer_desc: "High-level regional coordinators. Command emergency action plans, oversee cross-gate statistics, and sign off shift handovers."
  },
  es: {
    dashboard_title: "Plataforma del Sistema Montery",
    section_ops_header: "Centro de Comando de Operaciones",
    section_fan_header: "Compañero de Orientación para Fanáticos",
    section_volunteer_header: "Informes de Campo de Voluntarios",
    label_queue_volume: "Colas de Torniquetes del Perímetro",
    label_wait_time: "Tiempo de Espera Previsto",
    label_gate_throughput: "Tasa de Flujo de Rendimento",
    label_handover_summary: "Resumen de Entrega del Supervisor",
    label_restricted_warning: "Restringido: Se Requiere Autorización Administrativa",
    btn_select_role: "Seleccione su Rol de Acceso de Persona",
    btn_step_free: "Opción de Ruta ADA Libre de Pasos",
    spectator_deck_login: "Inicio de Sesión de Espectador (FAN)",
    secure_portal_entry: "ENTRADA DE PORTAL SEGURO",
    back_to_identities: "VOLVER A IDENTIDADES",
    full_name: "Nombre Completo",
    phone_number: "Número de Teléfono",
    volunteer_name: "Nombre del Voluntario",
    assigned_stadium: "Estadio de Partido Asignado",
    volunteer_number_3_digits: "Número de Voluntario (3 dígitos)",
    test_account_details: "DETALLES DE LA CUENTA DE PRUEBA:",
    sync_companion_deck: "REGISTRAR Y SINCRONIZAR DECK",
    digital_twin_workspace: "Espacio de Trabajo de Simulación de Gemelo Digital 3D",
    home_view: "Vista de Inicio",
    expand_view: "Expandir Vista",
    shrink_view: "Reducir Vista",
    interactive_scanner_active: "ESCÁNER INTERACTIVO ACTIVO",
    incident_registry: "REGISTRO DE INCIDENTES",
    mux_control_panel: "PANEL DE CONTROL MUX",
    fifa_tactical_deck: "PLATAFORMA TÁCTICA FIFA WC 2026",
    step_free_routing: "Ruta sin Escalones",
    ada_assisted_navigation: "NAVEGACIÓN ASISTIDA ADA",
    welcome_desc: "Bienvenido a Montery Smart Stadium Suite, una plataforma avanzada de auditoría de telemetría y gemelos digitales. Su terminal está actualmente sin asignar. Seleccione su perfil operativo autorizado a continuación para sincronizar sensores, iniciar transmisiones de cámara y habilitar matrices de análisis situacional.",
    fan_desc: "Registre su identidad de espectador. Estos datos se sincronizarán de forma segura y se conservarán en nuestra base de datos en la nube.",
    volunteer_desc: "Ingrese su identidad de voluntario. Solo se permiten voluntarios autorizados registrados en partidos oficiales.",
    staff_desc: "Autentíquese con sus credenciales designadas del personal de operaciones.",
    organizer_desc: "Autentíquese con los parámetros de coordinador regional de alto nivel.",
    role_fan_title: "Cubierta de Espectadores (FAN)",
    role_fan_desc: "Espectadores generales. Acceso a orientación, concesiones, direcciones de transporte y políticas básicas.",
    role_volunteer_title: "Soporte de Campo (VOLUNTARIO)",
    role_volunteer_desc: "Flujo de voluntarios en el terreno. Ayuda a gestionar colas, resolver problemas de visitantes y ver informes.",
    role_staff_title: "Terminal de Operaciones (PERSONAL DE SEDE)",
    role_staff_desc: "Monitorea imágenes de CCTV, audita anomalías de entradas y ejecuta diagnósticos de instalaciones.",
    role_organizer_title: "Coordinador Regional (ORGANIZADOR)",
    role_organizer_desc: "Coordinadores regionales de alto nivel. Dirige planes de acción de emergencia y supervisa estadísticas."
  },
  fr: {
    dashboard_title: "Plateforme du Système Montery",
    section_ops_header: "Centre de Commandement des Opérations",
    section_fan_header: "Compagnon d'Orientation des Supporters",
    section_volunteer_header: "Rapports de Terrain des Bénévoles",
    label_queue_volume: "Files d'Attente des Tourniquets du Périmètre",
    label_wait_time: "Temps d'Attente Prévu",
    label_gate_throughput: "Débit de Passage",
    label_handover_summary: "Résumé de Passation du Superviseur",
    label_restricted_warning: "Restreint: Autorisation Administrative Requise",
    btn_select_role: "Sélectionnez votre rôle d'accès",
    btn_step_free: "Option d'itinéraire sans marches",
    spectator_deck_login: "Connexion Spectateur (FAN)",
    secure_portal_entry: "ENTRÉE SÉCURISÉE DU PORTAIL",
    back_to_identities: "RETOUR AUX IDENTITÉS",
    full_name: "Nom Complet",
    phone_number: "Numéro de Téléphone",
    volunteer_name: "Nom du Bénévole",
    assigned_stadium: "Stade du Match Assigné",
    volunteer_number_3_digits: "Numéro de Bénévole (3 Chiffres)",
    test_account_details: "DÉTAILS DU COMPTE TEST:",
    sync_companion_deck: "ENREGISTRER & SYNCHRONISER LE COMPAGNON",
    digital_twin_workspace: "Espace de Simulation du Jumeau Numérique 3D",
    home_view: "Vue d'Accueil",
    expand_view: "Agrandir la Vue",
    shrink_view: "Réduire la Vue",
    interactive_scanner_active: "SCANNER INTERACTIF ACTIF",
    incident_registry: "REGISTRE DES INCIDENTS",
    mux_control_panel: "PANNEAU DE CONTRÔLE MUX",
    fifa_tactical_deck: "PONT TACTIQUE FIFA WC 2026",
    step_free_routing: "Itinéraire sans Marches",
    ada_assisted_navigation: "NAVIGATION ASSISTÉE ADA",
    welcome_desc: "Bienvenue dans la suite Montery Smart Stadium, une plateforme avancée de jumeau numérique et d'audit de télémétrie. Votre terminal n'est actuellement pas attribué. Veuillez sélectionner votre profil opérationnel autorisé ci-dessous pour synchroniser les capteurs, initialiser les flux de caméras et activer les matrices d'analyse situationnelle.",
    fan_desc: "Enregistrez votre identité de spectateur. Ces données seront synchronisées et conservées en toute sécurité dans notre base de données cloud.",
    volunteer_desc: "Veuillez entrer votre identité de bénévole. Seuls les bénévoles autorisés inscrits aux matchs officiels sont autorisés.",
    staff_desc: "Authentifiez-vous avec vos identifiants de personnel opérationnel désignés.",
    organizer_desc: "Authentifiez-vous avec les paramètres de coordinateur régional de haut niveau.",
    role_fan_title: "Espace Spectateur (FAN)",
    role_fan_desc: "Spectateurs généraux. Accès au plan, aux concessions, aux transports et aux règles de l'arène.",
    role_volunteer_title: "Soutien de Terrain (BÉNÉVOLE)",
    role_volunteer_desc: "Bénévoles sur place. Aide à gérer les files d'attente, à résoudre les problèmes et à voir les rapports.",
    role_staff_title: "Terminal d'Opérations (PERSONNEL DU STADE)",
    role_staff_desc: "Surveillance des caméras CCTV, audit des billets et diagnostics des installations.",
    role_organizer_title: "Coordinateur Régional (ORGANISATEUR)",
    role_organizer_desc: "Coordinateurs de haut niveau. Gestion des plans d'urgence et supervision des statistiques."
  },
  de: {
    dashboard_title: "Montery Systemplattform",
    section_ops_header: "Operations-Kommandozentrale",
    section_fan_header: "Fan-Wegweiser-Begleiter",
    section_volunteer_header: "Feldberichterstattung der Freiwilligen",
    label_queue_volume: "Warteschlangen am Drehkreuz",
    label_wait_time: "Prognostizierte Wartezeit",
    label_gate_throughput: "Durchsatz-Flussrate",
    label_handover_summary: "Übergabebericht des Supervisors",
    label_restricted_warning: "Eingeschränkt: Administrative Freigabe Erforderlich",
    btn_select_role: "Wählen Sie Ihre Persona-Zugriffsrolle",
    btn_step_free: "Stufenfreie ADA-Routenoption",
    spectator_deck_login: "Zuschauer-Login (FAN)",
    secure_portal_entry: "SICHERER PORTALZUGANG",
    back_to_identities: "ZURÜCK ZU IDENTITÄTEN",
    full_name: "Vollständiger Name",
    phone_number: "Telefonnummer",
    volunteer_name: "Name des Freiwilligen",
    assigned_stadium: "Zugewiesenes Spielstadion",
    volunteer_number_3_digits: "Freiwilligennummer (3-stellig)",
    test_account_details: "TESTKONTO-DETAILS:",
    sync_companion_deck: "BEGLEIT-DECK REGISTRIEREN & SYNCHRONISIEREN",
    digital_twin_workspace: "3D Digital Twin Simulationsarbeitsplatz",
    home_view: "Startansicht",
    expand_view: "Ansicht Erweitern",
    shrink_view: "Ansicht Verkleinern",
    interactive_scanner_active: "INTERAKTIVER SCANNER AKTIV",
    incident_registry: "INCIDENT-REGISTER",
    mux_control_panel: "MUX-KONTROLLZENTRUM",
    fifa_tactical_deck: "FIFA WM 2026 TAKTIK-DECK",
    step_free_routing: "Stufenfreie Route",
    ada_assisted_navigation: "ADA-UNTERSTÜTZTE NAVIGATION",
    welcome_desc: "Willkommen in der Montery Smart Stadium Suite, einer fortschrittlichen Plattform für digitale Zwillinge und Telemetrieaudits. Ihr Terminal ist derzeit nicht zugewiesen. Bitte wählen Sie unten Ihr autorisiertes Betriebsprofil aus, um Sensoren zu synchronisieren, Kamerastreams zu initialisieren und Situationsanalyse-Matrizen zu aktivieren.",
    fan_desc: "Registrieren Sie Ihre Zuschaueridentität. Diese Daten werden sicher synchronisiert und in unserer Cloud-Datenbank gespeichert.",
    volunteer_desc: "Bitte geben Sie Ihre Freiwilligenidentität ein. Es sind nur autorisierte Freiwillige zugelassen, die für offizielle Spiele registriert sind.",
    staff_desc: "Authentifizieren Sie sich mit den Zugangsdaten Ihres zugewiesenen Betriebspersonals.",
    organizer_desc: "Authentifizieren Sie sich mit den Parametern des regionalen Koordinators der oberen Ebene.",
    role_fan_title: "Zuschauer-Deck (FAN)",
    role_fan_desc: "Allgemeine Zuschauer. Zugang zu Wegweisern, Konzessionen, Verkehrsverbindungen und Arenapolitik.",
    role_volunteer_title: "Feldunterstützung (VOLUNTEER)",
    role_volunteer_desc: "Freiwillige vor Ort. Hilft bei Warteschlangen, löst Probleme und liest Berichte.",
    role_staff_title: "Betriebsterminal (VENUE STAFF)",
    role_staff_desc: "Überwachung von CCTV, Auditierung von Ticketanomalien und Anlagendiagnose.",
    role_organizer_title: "Regionaler Koordinator (ORGANIZER)",
    role_organizer_desc: "Hochrangige Koordinatoren. Befehligen Notfallpläne und überwachen Statistiken."
  },
  ja: {
    dashboard_title: "モントレー・システム・プラットフォーム",
    section_ops_header: "運行管理センター",
    section_fan_header: "ファン向けウェイファインダー・コンパニオン",
    section_volunteer_header: "ボランティア現地報告",
    label_queue_volume: "周辺改札口の行列",
    label_wait_time: "予測待ち時間",
    label_gate_throughput: "処理流量速度",
    label_handover_summary: "スーパーバイザー引き継ぎ要約",
    label_restricted_warning: "制限：管理者権限が必要です",
    btn_select_role: "アクセス権限ロールを選択",
    btn_step_free: "段差なしADAルートオプション",
    spectator_deck_login: "観客席ログイン (FAN)",
    secure_portal_entry: "セキュアポータルエントリー",
    back_to_identities: "ID一覧に戻る",
    full_name: "フルネーム",
    phone_number: "電話番号",
    volunteer_name: "ボランティア氏名",
    assigned_stadium: "割り当てられたスタジアム",
    volunteer_number_3_digits: "ボランティア番号（3桁）",
    test_account_details: "テストアカウント情報:",
    sync_companion_deck: "コンパニオンデッキを登録・同期",
    digital_twin_workspace: "3Dデジタルツイン・シミュレーションワークスペース",
    home_view: "ホーム表示",
    expand_view: "表示を拡大",
    shrink_view: "表示を縮小",
    interactive_scanner_active: "インタラクティブスキャナー起動中",
    incident_registry: "インシデント履歴レジストリ",
    mux_control_panel: "MUXコントロールパネル",
    fifa_tactical_deck: "FIFA WC 2026 タクティカルデッキ",
    step_free_routing: "段差なしルート",
    ada_assisted_navigation: "ADA支援ナビゲーション",
    welcome_desc: "モントレー・スマートスタジアム・スイートへようこそ。高度なデジタルツインとテレメトリ監査プラットフォームです。お使いの端末は現在未割り当てです。センサーの同期、カメラストリームの初期化、および状況分析マトリックスの有効化を行うには、以下から承認された操作プロファイルを選択してください。",
    fan_desc: "観客としての登録。このデータは、クラウドデータベースに安全に同期および保存されます。",
    volunteer_desc: "ボランティアの身元情報を入力してください。公式試合に登録されている承認済みのボランティアのみが許可されます。",
    staff_desc: "指定された運用スタッフ of 資格情報で認証してください。",
    organizer_desc: "上位の地域コーディネーター用パラメータで認証してください。",
    role_fan_title: "観客デッキ (FAN)",
    role_fan_desc: "一般の観客の皆様。スタジアム案内、売店情報、交通機関の案内、アリーナポリシーへのアクセス。",
    role_volunteer_title: "現場サポート (VOLUNTEER)",
    role_volunteer_desc: "現場ボランティア。行列の管理、来場者の問題解決、リアルタイムの混雑レポートの表示。",
    role_staff_title: "運行管理端末 (VENUE STAFF)",
    role_staff_desc: "管理室端末。CCTV映像の監視、発券異常の監査、ゲートや設備の診断実行。",
    role_organizer_title: "地域コーディネーター (ORGANIZER)",
    role_organizer_desc: "上位地域コーディネーター。緊急行動計画の指揮、クロスゲート統計の監視、引き継ぎ承認。"
  },
  ar: {
    dashboard_title: "منصة نظام مونتيري",
    section_ops_header: "مركز قيادة العمليات",
    section_fan_header: "دليل توجيه المشجعين",
    section_volunteer_header: "تقارير المتطوعين الميدانية",
    label_queue_volume: "طوابير بوابات الدوران المحيطية",
    label_wait_time: "وقت الانتظار المتوقع",
    label_gate_throughput: "معدل تدفق الإنتاجية",
    label_handover_summary: "ملخص تسليم المشرف",
    label_restricted_warning: "مقيد: مطلوب تصريح إداري",
    btn_select_role: "اختر دور الوصول الخاص بك",
    btn_step_free: "خيار مسار خالٍ من الدرج",
    spectator_deck_login: "تسجيل دخول المشجعين (FAN)",
    secure_portal_entry: "دخول بوابة آمن",
    back_to_identities: "العودة إلى الهويات",
    full_name: "الاسم الكامل",
    phone_number: "رقم الهاتف",
    volunteer_name: "اسم المتطوع",
    assigned_stadium: "الملعب المخصص للمباراة",
    volunteer_number_3_digits: "رقم المتطوع (3 أرقام)",
    test_account_details: "تفاصيل الحساب التجريبي:",
    sync_companion_deck: "تسجيل ومزامنة رفيق سطح السفينة",
    digital_twin_workspace: "مساحة عمل محاكاة التوأم الرقمي ثلاثي الأبعاد",
    home_view: "عرض الصفحة الرئيسية",
    expand_view: "توسيع العرض",
    shrink_view: "تقليص العرض",
    interactive_scanner_active: "الماسح الضوئي التفاعلي نشط",
    incident_registry: "سجل الحوادث",
    mux_control_panel: "لوحة تحكم MUX",
    fifa_tactical_deck: "منصة تكتيكية FIFA WC 2026",
    step_free_routing: "توجيه خالٍ من السلالم",
    ada_assisted_navigation: "الملاحة بمساعدة ADA",
    welcome_desc: "مرحبًا بك في جناح استاد مونتيري الذكي، وهو عبارة عن منصة تدقيق متطورة للتوأم الرقمي والقياس عن بُعد. محطتك الطرفية غير مخصصة حاليًا. يرجى تحديد ملف التشغيل المعتمد الخاص بك أدناه لمزامنة أجهزة الاستشعار وتهيئة تدفقات الكاميرا وتمكين مصفوفات تحليل الموقف.",
    fan_desc: "سجل هويتك كمشجع. ستتم مزامنة هذه البيانات بأمان والاحتفاظ بها في قاعدة بياناتنا السحابية.",
    volunteer_desc: "يرجى إدخال هويتك كمتطوع. يُسمح فقط للمتطوعين المعتمدين والمسجلين في المباريات الرسمية.",
    staff_desc: "قم بالمصادقة باستخدام أوراق اعتماد موظفي العمليات المعينين لديك.",
    organizer_desc: "قم بالمصادقة مع معلمات منسق المنطقة رفيع المستوى.",
    role_fan_title: "منصة المتفرجين (FAN)",
    role_fan_desc: "المتفرجون العامون. الوصول إلى توجيه المسار، التنازلات، اتجاهات النقل وسياسات الساحة.",
    role_volunteer_title: "الدعم الميداني (VOLUNTEER)",
    role_volunteer_desc: "المتطوعون في الميدان. المساعدة في إدارة الطوابير، معالجة مشكلات الزوار وتقارير الازدحام.",
    role_staff_title: "محطة العمليات (VENUE STAFF)",
    role_staff_desc: "مراقبة الدوائر التلفزيونية المغلقة، تدقيق تذاكر ومخالفات بوابات الدوران وتشخيص المرافق.",
    role_organizer_title: "المنسق الإقليمي (ORGANIZER)",
    role_organizer_desc: "منسقون إقليميون رفيعو المستوى. إدارة خطط الطوارئ والإشراف على إحصائيات بوابات الدوران."
  },
  pt: {
    dashboard_title: "Plataforma do Sistema Montery",
    section_ops_header: "Centro de Comando de Operações",
    section_fan_header: "Acompanhante de Orientação do Torcedor",
    section_volunteer_header: "Relatórios de Campo de Voluntários",
    label_queue_volume: "Filas de Catracas do Perímetro",
    label_wait_time: "Tempo de Espera Previsto",
    label_gate_throughput: "Taxa de Fluxo de Rendimento",
    label_handover_summary: "Resumo de Entrega do Supervisor",
    label_restricted_warning: "Restrito: Liberação Administrativa Necessária",
    btn_select_role: "Selecione o seu papel de acesso de persona",
    btn_step_free: "Opção de rota acessível sem degraus",
    spectator_deck_login: "Acesso ao Deck de Espectadores (FAN)",
    secure_portal_entry: "ENTRADA DE PORTAL SEGURO",
    back_to_identities: "VOLTAR ÀS IDENTIDADES",
    full_name: "Nome Completo",
    phone_number: "Número de Telefone",
    volunteer_name: "Nome do Voluntário",
    assigned_stadium: "Estádio do Jogo Atribuído",
    volunteer_number_3_digits: "Número do Voluntário (3 Dígitos)",
    test_account_details: "DETALHES DA CONTA DE TESTE:",
    sync_companion_deck: "REGISTRAR & SINCRONIZAR DECK DE COMPANHIA",
    digital_twin_workspace: "Espaço de Simulação do Gêmeo Digital 3D",
    home_view: "Vista Inicial",
    expand_view: "Expandir Vista",
    shrink_view: "Recortar Vista",
    interactive_scanner_active: "ESCANER INTERATIVO ATIVO",
    incident_registry: "REGISTRO DE INCIDENTES",
    mux_control_panel: "PAINEL DE CONTROLE MUX",
    fifa_tactical_deck: "DECK TÁTICO FIFA WC 2026",
    step_free_routing: "Rota sem Degraus",
    ada_assisted_navigation: "NAVEGAÇÃO ASSISTIDA ADA",
    welcome_desc: "Bem-vindo ao Montery Smart Stadium Suite, uma plataforma avançada de gêmeos digitais e auditoria de telemetria. Seu terminal está atualmente não atribuído. Selecione seu perfil operacional autorizado abaixo para sincronizar sensores, iniciar transmissões de câmera e habilitar matrizes de análise situacional.",
    fan_desc: "Registre sua identidade de espectador. Esses dados serão sincronizados de forma segura e persistidos em nosso banco de dados em nuvem.",
    volunteer_desc: "Insira sua identidade de voluntário. Apenas voluntários autorizados registrados em partidas oficiais são permitidos.",
    staff_desc: "Autentique-se com suas credenciais designadas da equipe de operações.",
    organizer_desc: "Autentique-se com os parâmetros do coordenador regional de alto nível.",
    role_fan_title: "Deck de Espectadores (FAN)",
    role_fan_desc: "Espectadores gerais. Acesso à orientação do layout, concessões, transporte e políticas básicas.",
    role_volunteer_title: "Suporte de Campo (VOLUNTÁRIO)",
    role_volunteer_desc: "Voluntários no terreno. Ajuda a gerenciar filas, resolver problemas e ver relatórios de tráfego.",
    role_staff_title: "Terminal de Operações (EQUIPE DO LOCAL)",
    role_staff_desc: "Monitoramento de câmeras, auditoria de irregularidades em ingressos e diagnósticos.",
    role_organizer_title: "Coordenador Regional (ORGANIZADOR)",
    role_organizer_desc: "Coordenadores regionais de alto nível. Comanda planos de emergência e supervisiona estatísticas."
  },
  it: {
    dashboard_title: "Piattaforma del Sistema Montery",
    section_ops_header: "Centro di Comando Operazioni",
    section_fan_header: "Compagno di Orientamento per i Tifosi",
    section_volunteer_header: "Rapporti sul Campo dei Volontari",
    label_queue_volume: "Code ai Tornelli del Perimetro",
    label_wait_time: "Tempo di Attesa Previsto",
    label_gate_throughput: "Tasso di Flusso di Transito",
    label_handover_summary: "Riepilogo del Passaggio di Consegna del Supervisore",
    label_restricted_warning: "Limitato: Richiesta Autorizzazione Amministrativa",
    btn_select_role: "Seleziona il Tuo Ruolo di Accesso Persona",
    btn_step_free: "Opzione di Percorso Senza Gradini",
    spectator_deck_login: "Accesso al Deck Spettatore (FAN)",
    secure_portal_entry: "ACCESSO PORTALE SICURO",
    back_to_identità: "TORNA ALLE IDENTITÀ",
    full_name: "Nome Completo",
    phone_number: "Numero di Telefono",
    volunteer_name: "Nome Volontario",
    assigned_stadium: "Stadio di Calcio Assegnato",
    volunteer_number_3_digits: "Numero Volontario (3 Cifre)",
    test_account_details: "DETTAGLI ACCOUNT DI PROVA:",
    sync_companion_deck: "REGISTRA E SINCRONIZZA COMPANION DECK",
    digital_twin_workspace: "Spazio di Simulazione del Gemello Digitale 3D",
    home_view: "Vista Iniziale",
    expand_view: "Espandi Vista",
    shrink_view: "Riduci Vista",
    interactive_scanner_active: "SCANNER INTERATTIVO ATTIVO",
    incident_registry: "REGISTRO INCIDENTI",
    mux_control_panel: "PANNELLO DI CONTROLLO MUX",
    fifa_tactical_deck: "DECK TATTICO FIFA WC 2026",
    step_free_routing: "Percorso senza Gradini",
    ada_assisted_navigation: "NAVIGAZIONE ASSISTITA ADA",
    welcome_desc: "Benvenuto nella suite Montery Smart Stadium, una piattaforma avanzata di gemello digitale e audit di telemetria. Il tuo terminale non è attualmente assegnato. Seleziona il tuo profilo operativo autorizzato di seguito per sincronizzare i sensori, inizializzare i flussi della telecamera e abilitare le matrici di analisi situazionale.",
    fan_desc: "Registra la tua identità di spettatore. Questi dati saranno sincronizzati in modo sicuro e persistenti nel nostro database cloud.",
    volunteer_desc: "Inserisci la tua identità di volontario. Sono ammessi solo i volontari autorizzati registrati per le partite ufficiali.",
    staff_desc: "Autenticati con le credenziali del personale operativo designate.",
    organizer_desc: "Autenticati con i parametri del coordinatore regionale di alto livello.",
    role_fan_title: "Piattaforma Spettatori (FAN)",
    role_fan_desc: "Spettatori generali. Accesso a indicazioni di layout, concessioni, trasporti e regolamento dell'arena.",
    role_volunteer_title: "Supporto sul Campo (VOLONTARIO)",
    role_volunteer_desc: "Volontari sul campo. Aiuta a gestire le code, risolvere i problemi dei visitatori e vedere i report.",
    role_staff_title: "Terminale Operazioni (PERSONALE SEDE)",
    role_staff_desc: "Monitoraggio CCTV, audit anomalie biglietti e diagnostica di impianti e cancelli.",
    role_organizer_title: "Coordinatore Regionale (ORGANIZZATORE)",
    role_organizer_desc: "Coordinatori di alto livello. Gestione dei piani d'emergenza e supervisione delle statistiche generali."
  },
  ko: {
    dashboard_title: "몬터레이 시스템 플랫폼",
    section_ops_header: "운영 명령 센터",
    section_fan_header: "팬 길찾기 컴패니언",
    section_volunteer_header: "자원봉사자 현장 보고",
    label_queue_volume: "외곽 회전식 문 대기열",
    label_wait_time: "예상 대기 시간",
    label_gate_throughput: "처리량 흐름 속도",
    label_handover_summary: "감독관 인수인계 요약",
    label_restricted_warning: "제한됨: 관리자 승인 필요",
    btn_select_role: "페르소나 액세스 역할 선택",
    btn_step_free: "계단 없는 ADA 경로 옵션",
    spectator_deck_login: "관람객 가상 덱 로그인 (FAN)",
    secure_portal_entry: "보안 포털 액세스",
    back_to_identities: "역할 선택으로 돌아가기",
    full_name: "성명",
    phone_number: "전화번호",
    volunteer_name: "자원봉사자 이름",
    assigned_stadium: "배정된 경기 스타디움",
    volunteer_number_3_digits: "자원봉사자 번호 (3자리)",
    test_account_details: "테스트 계정 정보:",
    sync_companion_deck: "컴패니언 덱 등록 및 동기화",
    digital_twin_workspace: "3D 디지털 트윈 시뮬레이션 워크스페이스",
    home_view: "기본 뷰",
    expand_view: "뷰 확장",
    shrink_view: "뷰 축소",
    interactive_scanner_active: "인터랙티브 스캐너 활성화됨",
    incident_registry: "인시던트 레지스트리",
    mux_control_panel: "MUX 제어 패널",
    fifa_tactical_deck: "FIFA WC 2026 전술 덱",
    step_free_routing: "계단 없는 경로",
    ada_assisted_navigation: "ADA 지원 내비게이션",
    welcome_desc: "몬터레이 스마트 스타디움 스위트에 오신 것을 환영합니다. 이 고급 디지털 트윈 및 텔레메트리 감사 플랫폼에서 사용자의 터미널은 현재 할당되지 않은 상태입니다. 센서를 동기화하고 카메라 스트림을 활성화하며 상황 분석 매트릭스를 활성화하려면 아래에서 공인된 운영 프로필을 선택하십시오.",
    fan_desc: "관객 신원을 등록하십시오. 이 데이터는 클라우드 데이터베이스에 안전하게 동기화되고 유지됩니다.",
    volunteer_desc: "자원봉사자 신원을 입력하십시오. 공식 경기에 등록된 공인 자원봉사자만 액세스할 수 있습니다.",
    staff_desc: "지정된 운영 부서의 권한 파일로 인증하십시오.",
    organizer_desc: "고위 지역 코디네이터 전용 매개변수로 인증하십시오.",
    role_fan_title: "관람객 덱 (FAN)",
    role_fan_desc: "일반 관람객 전용. 경기장 안내, 매점 정보, 교통편 경로 및 기본 아레나 규정 조회.",
    role_volunteer_title: "현장 자원봉사 (VOLUNTEER)",
    role_volunteer_desc: "현장 봉사자. 대기열 관리, 관람객 민원 해결 및 실시간 게이트 혼잡도 보고서 조회.",
    role_staff_title: "운영 제어 터미널 (VENUE STAFF)",
    role_staff_desc: "제어실 단말기. CCTV 화면 모니터링, 티켓팅 오류 심사, 시설 및 게이트 진단 검사 수행.",
    role_organizer_title: "지역 코디네이터 (ORGANIZER)",
    role_organizer_desc: "고위 지역 코디네이터. 비상 대책 계획 수립, 관문 간 통계 감독 및 교대 근무 승인."
  },
  zh: {
    dashboard_title: "蒙特雷系统平台",
    section_ops_header: "运营指挥中心",
    section_fan_header: "球迷寻路助手",
    section_volunteer_header: "志愿者现场报告",
    label_queue_volume: "外围闸机排队",
    label_wait_time: "预测等待时间",
    label_gate_throughput: "吞吐流量速率",
    label_handover_summary: "主管交接摘要",
    label_restricted_warning: "受限：需要管理许可",
    btn_select_role: "选择您的角色访问权限",
    btn_step_free: "无障碍免台阶路线选项",
    spectator_deck_login: "观众看台登录 (FAN)",
    secure_portal_entry: "安全门户入口",
    back_to_identities: "返回角色选择",
    full_name: "完整姓名",
    phone_number: "电话号码",
    volunteer_name: "志愿者姓名",
    assigned_stadium: "分配的比赛体育场",
    volunteer_number_3_digits: "志愿者编号（3位数字）",
    test_account_details: "测试账户信息:",
    sync_companion_deck: "注册并同步伴侣看板",
    digital_twin_workspace: "3D数字孪生模拟工作空间",
    home_view: "主视图",
    expand_view: "展开视图",
    shrink_view: "收起视图",
    interactive_scanner_active: "交互式扫描器已激活",
    incident_registry: "事件登记库",
    mux_control_panel: "MUX 控制面板",
    fifa_tactical_deck: "FIFA WC 2026 战术甲板",
    step_free_routing: "无台阶路线",
    ada_assisted_navigation: "ADA 辅助导航",
    welcome_desc: "欢迎来到蒙特雷智能体育场套件，这是一个先进 of 数字孪生和遥测审计平台。您的终端目前未分配。请在下方选择您授权的运营配置文件，以同步传感器、初始化摄像机流并启用态势分析矩阵。",
    fan_desc: "注册您的观众身份。此数据将被安全同步并持久化到我们的云端数据库中。",
    volunteer_desc: "请输入您的志愿者身份。仅允许在官方比赛注册的授权志愿者访问。",
    staff_desc: "请使用您指定的运营人员凭据进行身份验证。",
    organizer_desc: "请使用高级区域协调员参数进行身份验证。",
    role_fan_title: "观众看台 (FAN)",
    role_fan_desc: "普通观众。访问场馆地图导航、餐饮选购、交通指引及基础场馆规章。",
    role_volunteer_title: "现场支持 (VOLUNTEER)",
    role_volunteer_desc: "一线志愿服务。协助维护排队秩序、解决访客求助并查看实时通道拥堵报告。",
    role_staff_title: "场馆运营终端 (VENUE STAFF)",
    role_staff_desc: "中控室终端。监视实时监控、审查闸机异常票务并对通道设备运行诊断。",
    role_organizer_title: "区域总协调员 (ORGANIZER)",
    role_organizer_desc: "高层区域负责人。发布紧急行动预案、统筹各通道全局统计并签发交接班确认。"
  },
  nl: {
    dashboard_title: "Montery Systeemplatform",
    section_ops_header: "Ops Commandocentrum",
    section_fan_header: "Fan Wegwijzer Partner",
    section_volunteer_header: "Veldrapportage Vrijwilligers",
    label_queue_volume: "Wachtrijen bij de Draaihekken",
    label_wait_time: "Voorspelde Wachttijd",
    label_gate_throughput: "Doorstroomcapaciteit",
    label_handover_summary: "Overdrachtsrapport Supervisor",
    label_restricted_warning: "Beperkt: Administratieve Vrijgave Vereist",
    btn_select_role: "Selecteer Uw Persona Toegangsrol",
    btn_step_free: "Stapvrije ADA-Routeoptie",
    spectator_deck_login: "Toegang Toeschouwersdeck (FAN)",
    secure_portal_entry: "BEVEILIGDE PORTAALINGANG",
    back_to_identities: "TERUG NAAR IDENTITEITEN",
    full_name: "Volledige Naam",
    phone_number: "Telefoonnummer",
    volunteer_name: "Naam Vrijwilliger",
    assigned_stadium: "Toegewezen Wedstrijdstadion",
    volunteer_number_3_digits: "Vrijwilligersnummer (3-cijfers)",
    test_account_details: "TESTACC_DETAILS:",
    sync_companion_deck: "REGISTREER & SYNC COMPANION DECK",
    digital_twin_workspace: "3D Digital Twin Simulatiewerkruimte",
    home_view: "Standaardweergave",
    expand_view: "Weergave Vergroten",
    shrink_view: "Weergave Verkleinen",
    interactive_scanner_active: "INTERACTIEVE SCANNER ACTIEF",
    incident_registry: "INCIDENTENREGISTRIE",
    mux_control_panel: "MUX-CONTROLEPANEEL",
    fifa_tactical_deck: "FIFA WC 2026 TACTISCH DECK",
    step_free_routing: "Trapvrije Route",
    ada_assisted_navigation: "ADA ASSISTENTIE NAVIGATIE",
    welcome_desc: "Welkom bij de Montery Smart Stadium Suite, een geavanceerd digital twin- en telemetrie-auditplatform. Uw terminal is momenteel niet toegewezen. Selecteer hieronder uw geautoriseerde operationele profiel om sensoren te synchroniseren, camerastreams te initialiseren en situatieanalysematrices in te schakelen.",
    fan_desc: "Registreer uw toeschouwersidentiteit. Deze gegevens worden veilig gesynchroniseerd en opgeslagen in onze clouddatabase.",
    volunteer_desc: "Voer uw vrijwilligersidentiteit in. Alleen geautoriseerde vrijwilligers die zijn geregistreerd voor officiële wedstrijden zijn toegestaan.",
    staff_desc: "Identificeer uzelf met uw aangewezen operationele inloggegevens.",
    organizer_desc: "Identificeer uzelf met de parameters voor de regionale coördinator op hoog niveau.",
    role_fan_title: "Toeschouwersdeck (FAN)",
    role_fan_desc: "Algemene toeschouwers. Toegang tot de layout-navigatie, verkooppunten, transportrichtingen en arena-regels.",
    role_volunteer_title: "Veldondersteuning (VOLUNTEER)",
    role_volunteer_desc: "Vrijwilligers ter plaatse. Helpt bij wachtrijbeheer, lost bezoekersproblemen op en leest realtime rapporten.",
    role_staff_title: "Operationeel Terminal (VENUE STAFF)",
    role_staff_desc: "Controlekamerterminals. Bewaak CCTV-beelden, controleer ticketanomalieën en voer faciliteitendiagnostiek uit.",
    role_organizer_title: "Regionaal Coördinator (ORGANIZER)",
    role_organizer_desc: "Hooggeplaatste regionale coördinatoren. Geeft leiding aan noodplannen en houdt toezicht op statistieken."
  },
  hi: {
    dashboard_title: "मोंटेरी सिस्टम प्लेटफॉर्म",
    section_ops_header: "ऑप्स कमांड सेंटर",
    section_fan_header: "प्रशंसक मार्गदर्शक साथी",
    section_volunteer_header: "स्वयंसेवक क्षेत्र रिपोर्टिंग",
    label_queue_volume: "बाहरी टर्नस्टाइल कतारें",
    label_wait_time: "अनुमानित प्रतीक्षा समय",
    label_gate_throughput: "थ्रूपुट प्रवाह दर",
    label_handover_summary: "पर्यवेक्षक हैंडओवर सारांश",
    label_restricted_warning: "प्रतिबंधित: प्रशासनिक मंजूरी आवश्यक",
    btn_select_role: "अपनी व्यक्तिगत पहुंच भूमिका चुनें",
    btn_step_free: "सीढ़ी-मुक्त ADA मार्ग विकल्प",
    spectator_deck_login: "दर्शक डेक लॉगिन (FAN)",
    secure_portal_entry: "सुरक्षित पोर्टल प्रविष्टि",
    back_to_identities: "भूमिकाओं पर वापस जाएं",
    full_name: "पूरा नाम",
    phone_number: "फ़ोन नंबर",
    volunteer_name: "स्वयंसेवक का नाम",
    assigned_stadium: "आवंटित मैच स्टेडियम",
    volunteer_number_3_digits: "स्वयंसेवक कोड (3 अंक)",
    test_account_details: "परीक्षण खाता विवरण:",
    sync_companion_deck: "साथी डेक को पंजीकृत और सिंक करें",
    digital_twin_workspace: "3D डिजिटल ट्विन सिमुलेशन कार्यक्षेत्र",
    home_view: "मुख्य दृश्य",
    expand_view: "दृश्य विस्तृत करें",
    shrink_view: "दृश्य संकुचित करें",
    interactive_scanner_active: "इंटरैक्टिव स्कैनर सक्रिय",
    incident_registry: "दुर्घटना रजिस्ट्री",
    mux_control_panel: "MUX नियंत्रण कक्ष",
    fifa_tactical_deck: "FIFA WC 2026 सामरिक डेक",
    step_free_routing: "सीढ़ी-मुक्त मार्ग",
    ada_assisted_navigation: "ADA सहायक नेविगेशन",
    welcome_desc: "मोंटेरी स्मार्ट स्टेडियम सूट में आपका स्वागत है, जो एक उन्नत डिजिटल ट्विन और टेलीमेट्री ऑडिट प्लेटफॉर्म है। आपका टर्मिनल वर्तमान में असाइन नहीं है। सेंसर को सिंक करने, कैमरा स्ट्रीम शुरू करने और स्थिति विश्लेषण मैट्रिक्स को सक्षम करने के लिए कृपया नीचे अपना अधिकृत परिचालन प्रोफ़ाइल चुनें।",
    fan_desc: "अपनी दर्शक पहचान दर्ज करें। यह डेटा हमारे क्लाउड डेटाबेस में सुरक्षित रूप से सिंक और संग्रहीत किया जाएगा।",
    volunteer_desc: "कृपया अपनी स्वयंसेवक पहचान दर्ज करें। केवल आधिकारिक मैचों के साथ पंजीकृत अधिकृत स्वयंसेवकों को ही अनुमति है।",
    staff_desc: "अपने निर्दिष्ट परिचालन स्टाफ क्रेडेंशियल के साथ प्रमाणित करें।",
    organizer_desc: "उच्च-स्तरीय क्षेत्रीय समन्वयक मापदंडों के साथ प्रमाणित करें।",
    role_fan_title: "दर्शक डेक (FAN)",
    role_fan_desc: "सामान्य दर्शक। लेआउट मार्ग खोज, रियायतें, परिवहन निर्देश और बुनियादी क्षेत्र नीतियों तक पहुंच।",
    role_volunteer_title: "फील्ड सहायता (VOLUNTEER)",
    role_volunteer_desc: "जमीनी स्वयंसेवक धारा। कतारों का प्रबंधन करने, आगंतुकों के मुद्दों को हल करने और भीड़ की रिपोर्ट देखने में मदद करें।",
    role_staff_title: "संचालन टर्मिनल (VENUE STAFF)",
    role_staff_desc: "नियंत्रण कक्ष टर्मिनल। सीसीटीवी फुटेज की निगरानी करें, टिकट विसंगतियों का ऑडिट करें और सुविधाओं की जांच करें।",
    role_organizer_title: "क्षेत्रीय समन्वयक (ORGANIZER)",
    role_organizer_desc: "उच्च स्तरीय क्षेत्रीय समन्वयक। आपातकालीन कार्य योजनाओं का संचालन करें और गेट आंकड़ों की निगरानी करें।"
  }
};

function detectDictionaryLanguage(dict: Record<string, string>): string {
  let bestLang = 'en';
  let maxMatches = -1;

  for (const [lang, langDict] of Object.entries(LOCALIZED_DICTIONARIES)) {
    let matches = 0;
    const keysToCheck = ['dashboard_title', 'section_ops_header', 'section_fan_header'];
    for (const key of keysToCheck) {
      if (dict[key] && dict[key] === langDict[key]) {
        matches++;
      }
    }
    if (matches > maxMatches) {
      maxMatches = matches;
      bestLang = lang;
    }
  }
  return bestLang;
}

export function getTranslation(key: string, selectedLanguage: string, engineResult?: any): string {
  const customDict = SIDEBAR_TRANSLATIONS[selectedLanguage] || SIDEBAR_TRANSLATIONS['en'];
  if (customDict && customDict[key]) {
    return customDict[key];
  }

  const dict = LOCALIZED_DICTIONARIES[selectedLanguage] || LOCALIZED_DICTIONARIES['en'];
  
  if (engineResult?.ui_localized_dictionary) {
    const currentDictLang = detectDictionaryLanguage(engineResult.ui_localized_dictionary);
    if (currentDictLang === selectedLanguage && engineResult.ui_localized_dictionary[key]) {
      return engineResult.ui_localized_dictionary[key];
    }
  }

  if (dict && dict[key]) {
    return dict[key];
  }

  if (engineResult?.ui_localized_dictionary && engineResult.ui_localized_dictionary[key]) {
    return engineResult.ui_localized_dictionary[key];
  }

  return LOCALIZED_DICTIONARIES['en']?.[key] || key;
}

const SIDEBAR_TRANSLATIONS: { [lang: string]: { [key: string]: string } } = {
  en: {
    nav_digital_twin: "3D DIGITAL TWIN",
    nav_command_console: "COMMAND CONSOLE",
    nav_stadium_corpus: "STADIUM CORPUS",
    nav_spectator_registry: "SPECTATOR REGISTRY",
    nav_engine_decoder: "ENGINE DECODER",
    nav_firewall_logs: "FIREWALL LOGS",
    nav_stadium_chat: "GEMINI STADIUM CHAT",
    nav_status: "STATUS",
    nav_mux_panel: "MUX CONTROL PANEL",
    nav_tactical_deck: "FIFA WC 2026 TACTICAL DECK",
    stadium_corpus_grounding_manual: "STADIUM CORPUS & GROUNDING MANUAL",
    matrix_command_input_console: "Matrix Command Input Console",
    engine_output_decoded_payload: "Engine Output Decoded Payload",
    spectator_registry_database: "SPECTATOR REGISTRY DATABASE",
    firewall_security_logs: "FIREWALL SECURITY LOGS",
    gemini_compliance_chatbot: "GEMINI COMPLIANCE CHATBOT"
  },
  es: {
    nav_digital_twin: "GEMELO DIGITAL 3D",
    nav_command_console: "CONSOLA DE MANDO",
    nav_stadium_corpus: "CORPUS DEL ESTADIO",
    nav_spectator_registry: "REGISTRO DE ESPECTADORES",
    nav_engine_decoder: "DECODIFICADOR DE MOTOR",
    nav_firewall_logs: "LOGS DE FIREWALL",
    nav_stadium_chat: "CHAT DE ESTADIO GEMINI",
    nav_status: "ESTADO",
    nav_mux_panel: "PANEL DE CONTROL MUX",
    nav_tactical_deck: "PLATAFORMA TÁTICA FIFA WC 2026",
    stadium_corpus_grounding_manual: "CORPUS DEL ESTADIO Y MANUAL DE ORIENTACIÓN",
    matrix_command_input_console: "Consola de Entrada de Comandos de Matriz",
    engine_output_decoded_payload: "Carga Útil Decodificada de Salida de Motor",
    spectator_registry_database: "BASE DE DATOS DEL REGISTRO DE ESPECTADORES",
    firewall_security_logs: "LOGS DE SEGURIDAD DEL FIREWALL",
    gemini_compliance_chatbot: "CHATBOT DE CUMPLIMIENTO GEMINI"
  },
  fr: {
    nav_digital_twin: "JUMEAU NUMÉRIQUE 3D",
    nav_command_console: "CONSOLE DE COMMANDE",
    nav_stadium_corpus: "CORPUS DU STADE",
    nav_spectator_registry: "REGISTRE DES SPECTATEURS",
    nav_engine_decoder: "DÉCODEUR DE MOTEUR",
    nav_firewall_logs: "LOGS DE PARE-FEU",
    nav_stadium_chat: "CHAT DE STADE GEMINI",
    nav_status: "STATUT",
    nav_mux_panel: "PANNEAU DE CONTRÔLE MUX",
    nav_tactical_deck: "PONT TACTIQUE FIFA WC 2026",
    stadium_corpus_grounding_manual: "CORPUS DU STADE & MANUEL DE ROUTAGE",
    matrix_command_input_console: "Console d'Entrée des Commandes de Matrice",
    engine_output_decoded_payload: "Charge Utile Décodée du Moteur",
    spectator_registry_database: "BASE DE DONNÉES DU REGISTRE DES SPECTATEURS",
    firewall_security_logs: "LOGS DE SÉCURITÉ DU PARE-FEU",
    gemini_compliance_chatbot: "CHATBOT DE CONFORMITÉ GEMINI"
  },
  de: {
    nav_digital_twin: "3D DIGITALER ZWILLING",
    nav_command_console: "BEFEHLSKONSOLE",
    nav_stadium_corpus: "STADION-KORPUS",
    nav_spectator_registry: "ZUSCHAUER-REGISTER",
    nav_engine_decoder: "MOTOR-DECODER",
    nav_firewall_logs: "FIREWALL-PROTOKOLLE",
    nav_stadium_chat: "GEMINI STADION-CHAT",
    nav_status: "STATUS",
    nav_mux_panel: "MUX-KONTROLLZENTRUM",
    nav_tactical_deck: "FIFA WM 2026 TAKTIK-DECK",
    stadium_corpus_grounding_manual: "STADION-KORPUS & BODENHANDBUCH",
    matrix_command_input_console: "Matrix-Befehlseingabekonsole",
    engine_output_decoded_payload: "Decodierte Nutzlast der Motor-Ausgabe",
    spectator_registry_database: "ZUSCHAUER-REGISTER-DATENBANK",
    firewall_security_logs: "FIREWALL-SICHERHEITSPROTOKOLLE",
    gemini_compliance_chatbot: "GEMINI COMPLIANCE-CHATBOT"
  },
  ja: {
    nav_digital_twin: "3Dデジタルツイン",
    nav_command_console: "コマンドコンソール",
    nav_stadium_corpus: "スタジアムコーパス",
    nav_spectator_registry: "観客登録レジストリ",
    nav_engine_decoder: "エンジンデコーダ",
    nav_firewall_logs: "ファイアウォールログ",
    nav_stadium_chat: "GEMINIスタジアムチャット",
    nav_status: "ステータス",
    nav_mux_panel: "MUXコントロールパネル",
    nav_tactical_deck: "FIFA WC 2026 タクティカルデッキ",
    stadium_corpus_grounding_manual: "スタジアムコーパス＆グラウンディングマニュアル",
    matrix_command_input_console: "マトリックスコマンド入力コンソール",
    engine_output_decoded_payload: "エンジン出力デコード済みペイロード",
    spectator_registry_database: "観客登録レジストリ・データベース",
    firewall_security_logs: "ファイアウォール・セキュリティログ",
    gemini_compliance_chatbot: "GEMINIコンプライアンス・チャットボット"
  },
  ar: {
    nav_digital_twin: "التوأم الرقمي ثلاثي الأبعاد",
    nav_command_console: "وحدة التحكم بالأوامر",
    nav_stadium_corpus: "مجموعة بيانات الاستاد",
    nav_spectator_registry: "سجل المتفرجين",
    nav_engine_decoder: "فك ترميز المحرك",
    nav_firewall_logs: "سجلات جدار الحماية",
    nav_stadium_chat: "دردشة استاد جيمني",
    nav_status: "الحالة",
    nav_mux_panel: "لوحة تحكم MUX",
    nav_tactical_deck: "منصة تكتيكية FIFA WC 2026",
    stadium_corpus_grounding_manual: "مجموعة بيانات الاستاد ودليل التوجيه",
    matrix_command_input_console: "وحدة إدخال أوامر المصفوفة",
    engine_output_decoded_payload: "حمولة مفككة لترميز إخراج المحرك",
    spectator_registry_database: "قاعدة بيانات سجل المتفرجين",
    firewall_security_logs: "سجلات أمان جدار الحماية",
    gemini_compliance_chatbot: "برنامج الدردشة الآلي للامتثال لـ جيمني"
  },
  pt: {
    nav_digital_twin: "GÊMEO DIGITAL 3D",
    nav_command_console: "CONSOLE DE COMANDO",
    nav_stadium_corpus: "CORPUS DO ESTÁDIO",
    nav_spectator_registry: "REGISTRO DE ESPECTADORES",
    nav_engine_decoder: "DECODIFICADOR DE MOTOR",
    nav_firewall_logs: "LOGS DE FIREWALL",
    nav_stadium_chat: "CHAT DE ESTÁDIO GEMINI",
    nav_status: "STATUS",
    nav_mux_panel: "PAINEL DE CONTROLE MUX",
    nav_tactical_deck: "DECK TÁTICO FIFA WC 2026",
    stadium_corpus_grounding_manual: "CORPUS DO ESTÁDIO E MANUAL DE ORIENTAÇÃO",
    matrix_command_input_console: "Console de Entrada de Comandos de Matriz",
    engine_output_decoded_payload: "Carga Útil Decodificada de Saída do Motor",
    spectator_registry_database: "BANCO DE DADOS DO REGISTRO DE ESPECTADORES",
    firewall_security_logs: "LOGS DE SEGURANÇA DO FIREWALL",
    gemini_compliance_chatbot: "CHATBOT DE CONFORMIDADE GEMINI"
  },
  it: {
    nav_digital_twin: "GEMELLO DIGITALE 3D",
    nav_command_console: "CONSOLE DI COMANDO",
    nav_stadium_corpus: "CORPUS DELLO STADIO",
    nav_spectator_registry: "REGISTRO SPETTATORI",
    nav_engine_decoder: "DECODER DI MOTORE",
    nav_firewall_logs: "LOG DEL FIREWALL",
    nav_stadium_chat: "CHAT DELLO STADIO GEMINI",
    nav_status: "STATO",
    nav_mux_panel: "PANNELLO DI CONTROLLO MUX",
    nav_tactical_deck: "DECK TATTICO FIFA WC 2026",
    stadium_corpus_grounding_manual: "CORPUS DELLO STADIO E MANUALE DI ORIENTAMENTO",
    matrix_command_input_console: "Console di Input dei Comandi della Matrice",
    engine_output_decoded_payload: "Carico Utile Decodificato dell'Uscita del Motore",
    spectator_registry_database: "DATABASE DEL REGISTRO DEGLI SPETTATORI",
    firewall_security_logs: "LOG DI SICUREZZA DEL FIREWALL",
    gemini_compliance_chatbot: "CHATBOT DI CONFORMITÀ GEMINI"
  },
  ko: {
    nav_digital_twin: "3D 디지털 트윈",
    nav_command_console: "명령 콘솔",
    nav_stadium_corpus: "스타디움 코퍼스",
    nav_spectator_registry: "관람객 레지스트리",
    nav_engine_decoder: "엔진 디코더",
    nav_firewall_logs: "방화벽 로그",
    nav_stadium_chat: "GEMINI 스타디움 채팅",
    nav_status: "상태",
    nav_mux_panel: "MUX 제어 패널",
    nav_tactical_deck: "FIFA WC 2026 전술 덱",
    stadium_corpus_grounding_manual: "스타디움 코퍼스 및 그라운딩 매뉴얼",
    matrix_command_input_console: "매트릭스 명령 입력 콘솔",
    engine_output_decoded_payload: "엔진 출력 디코딩된 페이로드",
    spectator_registry_database: "관람객 등록 데이터베이스",
    firewall_security_logs: "방화벽 보안 로그",
    gemini_compliance_chatbot: "GEMINI 컴플라이언스 챗봇"
  },
  zh: {
    nav_digital_twin: "3D 数字孪生",
    nav_command_console: "命令控制台",
    nav_stadium_corpus: "体育场语料库",
    nav_spectator_registry: "观众登记库",
    nav_engine_decoder: "引擎解码器",
    nav_firewall_logs: "防火墙日志",
    nav_stadium_chat: "GEMINI 体育场聊天",
    nav_status: "状态",
    nav_mux_panel: "MUX 控制面板",
    nav_tactical_deck: "FIFA WC 2026 战术甲板",
    stadium_corpus_grounding_manual: "体育场语料库与引导手册",
    matrix_command_input_console: "矩阵命令输入控制台",
    engine_output_decoded_payload: "引擎输出已解码负载",
    spectator_registry_database: "观众登记数据库",
    firewall_security_logs: "防火墙安全日志",
    gemini_compliance_chatbot: "GEMINI 合规聊天机器人"
  },
  nl: {
    nav_digital_twin: "3D DIGITAL TWIN",
    nav_command_console: "COMMANDOCONSOLE",
    nav_stadium_corpus: "STADION-CORPUS",
    nav_spectator_registry: "TOESCHOUWERS-REGISTER",
    nav_engine_decoder: "MOTORDECODER",
    nav_firewall_logs: "FIREWALL-LOGS",
    nav_stadium_chat: "GEMINI STADION-CHAT",
    nav_status: "STATUS",
    nav_mux_panel: "MUX-CONTROLEPANEEL",
    nav_tactical_deck: "FIFA WC 2026 TACTISCH DECK",
    stadium_corpus_grounding_manual: "STADION-CORPUS & GRONDINGSHANDLEIDING",
    matrix_command_input_console: "Matrix Commandolink Console",
    engine_output_decoded_payload: "Gedecodeerde Payload van Motor-output",
    spectator_registry_database: "TOESCHOUWERSREGISTRATIE DATABASE",
    firewall_security_logs: "FIREWALL BEVEILIGINGSLOGS",
    gemini_compliance_chatbot: "GEMINI NALEVING CHATBOT"
  },
  hi: {
    nav_digital_twin: "3D डिजिटल ट्विन",
    nav_command_console: "कमांड कंसोल",
    nav_stadium_corpus: "स्टेडियम कॉर्पस",
    nav_spectator_registry: "दर्शक रजिस्ट्री",
    nav_engine_decoder: "इंजन डिकोडर",
    nav_firewall_logs: "फ़ायरवॉल लॉग",
    nav_stadium_chat: "GEMINI स्टेडियम चैट",
    nav_status: "स्थिति",
    nav_mux_panel: "MUX नियंत्रण कक्ष",
    nav_tactical_deck: "FIFA WC 2026 सामरिक डेक",
    stadium_corpus_grounding_manual: "स्टेडियम कॉर्पस और ग्राउंडिंग मैनुअल",
    matrix_command_input_console: "मैट्रिक्स कमांड इनपुट कंसोल",
    engine_output_decoded_payload: "इंजन आउटपुट डिकोड किया गया पेलोड",
    spectator_registry_database: "दर्शक रजिस्ट्री डेटाबेस",
    firewall_security_logs: "फ़ायरवॉल सुरक्षा लॉग",
    gemini_compliance_chatbot: "GEMINI अनुपालन चैटबॉट"
  }
};
